#pragma once

namespace fastrecord::ui {

inline constexpr wchar_t kAppPage[] = LR"HTML(
<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:dark;--bg:#08090c;--surface:#101217;--line:#252933;--text:#f5f6f8;--muted:#858b99;--red:#ff3b45}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:transparent;color:var(--text);font-family:"Segoe UI Variable","Segoe UI",sans-serif;-webkit-user-select:none;user-select:none}
button,select{font:inherit;color:inherit}button{border:0;cursor:pointer}.app{height:100%;background:radial-gradient(circle at 18% 0,rgba(255,59,69,.07),transparent 24%),var(--bg);border:0;border-radius:18px;overflow:hidden;display:grid;grid-template-rows:56px 158px 96px 44px 1fr;box-shadow:inset 0 0 0 1px #30343e}
.header{display:flex;align-items:center;padding:0 16px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:9px;flex:1}.mark{width:20px;height:20px;border:6px solid var(--red);border-top-color:#5c2228;border-radius:50%;transform:rotate(-35deg)}.name{font-size:15px;font-weight:650}.version{font-size:10px;color:#5e6471;margin-left:4px}.window-actions{display:flex;gap:2px}.icon-btn{width:31px;height:31px;border-radius:8px;background:transparent;color:#969ca9;display:grid;place-items:center}.icon-btn:hover{background:#191c23;color:white}.icon-btn.active{color:var(--red)}.icon{width:17px;height:17px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
.actions{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;padding:14px 17px 10px}.action{background:transparent;border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px}.action:hover{background:#111319}.orb{width:62px;height:62px;border-radius:50%;background:#191c23;display:grid;place-items:center;color:#9da2ae;transition:.16s}.action:hover .orb{transform:translateY(-2px);background:#20232b}.action.record .orb{background:linear-gradient(145deg,#ff4a53,#ed2632);color:white;box-shadow:0 0 0 7px #ff36420e,0 7px 22px #ff263e38}.action:disabled{cursor:default;opacity:.38}.action-title{font-size:12px}.shortcut{font-size:9px;color:#747a88}.record-dot{width:20px;height:20px;border-radius:50%;background:#fff}.pause-glyph{display:flex;gap:6px}.pause-glyph i{display:block;width:5px;height:20px;border-radius:2px;background:currentColor}.stop-glyph{width:19px;height:19px;border-radius:2px;background:currentColor}
.sources{display:grid;grid-template-columns:1fr 1fr 1.18fr;gap:7px;padding:6px 13px 10px}.source{background:var(--surface);border:1px solid #171a20;border-radius:12px;padding:11px 10px;display:grid;grid-template-columns:17px minmax(0,1fr) auto;grid-template-rows:19px 17px;column-gap:6px;align-content:center}.source>.icon{grid-column:1;grid-row:1;color:#c8ccd4;width:16px;height:16px}.source-title{grid-column:2;grid-row:1;font-size:10px;line-height:17px;white-space:nowrap}.source-state{grid-column:2/4;grid-row:2;font-size:9px;color:var(--muted);line-height:16px}.toggle{grid-column:3;grid-row:1;width:30px;height:17px;border-radius:20px;background:#353944;padding:2px;align-self:center}.toggle:after{content:"";display:block;width:13px;height:13px;border-radius:50%;background:#d8dbe1;transition:.16s}.toggle.on{background:var(--red)}.toggle.on:after{transform:translateX(13px);background:white}
.tabs{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #181b22;border-bottom:1px solid var(--line);padding:0 12px}.tab{position:relative;background:transparent;color:#777d8a;font-size:11px;display:flex;align-items:center;justify-content:center;gap:7px}.tab .icon{width:15px;height:15px}.tab:hover{color:#d4d7dd}.tab.active{color:var(--red);font-weight:600}.tab.active:after{content:"";position:absolute;height:2px;left:18px;right:18px;bottom:-1px;background:var(--red)}
.content{min-height:0;padding:8px 14px}.pane{height:100%;display:none}.pane.active{display:flex}.empty{width:100%;height:100%;border:1px solid #171a21;border-radius:12px;background:linear-gradient(180deg,#101217,#0d0f13);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.empty-icon{width:40px;height:40px;border-radius:50%;background:#181b22;color:#666d7a;display:grid;place-items:center;margin-bottom:9px}.empty strong{font-size:12px;font-weight:500}.empty span{font-size:9px;color:var(--muted);margin-top:5px}.panel-list{width:100%;display:flex;flex-direction:column;gap:5px}.panel-title{font-size:9px;text-transform:uppercase;letter-spacing:.8px;color:#686e7b;margin:0 0 1px 3px}.setting{display:flex;align-items:center;min-height:46px;background:var(--surface);border:1px solid #181b22;border-radius:11px;padding:6px 9px;gap:9px}.setting>.icon{color:#9ea4b0}.setting-copy{min-width:0;flex:1}.setting-name{font-size:11px}.setting-note{font-size:9px;color:var(--muted);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.secondary{background:#1a1d24;border:1px solid #292d37;border-radius:8px;padding:7px 9px;font-size:10px}.secondary:hover{background:#22252d}.hotkey{font-size:10px;color:#c9cdd5;background:#20232a;border:1px solid #30343e;border-radius:6px;padding:4px 7px}
.custom-select{position:relative;width:132px}.source .custom-select{grid-column:2/4;grid-row:2;width:100%;align-self:end}.select-trigger{width:100%;height:31px;padding:0 9px;display:flex;align-items:center;justify-content:space-between;gap:8px;background:#171a20;border:1px solid #2b303a;border-radius:8px;font-size:10px;text-align:left}.source .select-trigger{height:17px;padding:0;background:transparent;border:0;border-radius:0;color:var(--muted);font-size:9px}.select-trigger:hover,.custom-select.open .select-trigger{border-color:#414754;background:#1b1e25}.source .select-trigger:hover,.source .custom-select.open .select-trigger{background:transparent;border-color:transparent;color:#d9dce2}.chevron{width:6px;height:6px;border-right:1.5px solid currentColor;border-bottom:1.5px solid currentColor;transform:rotate(45deg) translateY(-2px);transition:transform .14s}.custom-select.open .chevron{transform:rotate(225deg) translate(-1px,-1px)}.select-menu{display:none;position:absolute;z-index:50;top:calc(100% + 6px);right:0;min-width:100%;padding:5px;background:#15181e;border:1px solid #303540;border-radius:9px;box-shadow:0 14px 32px #000b}.custom-select.open .select-menu{display:grid;gap:2px}.select-option{position:relative;width:100%;min-width:126px;padding:7px 9px 7px 22px;border-radius:6px;background:transparent;color:#aeb3bd;font-size:10px;text-align:left;white-space:nowrap}.select-option:hover{background:#20242c;color:#fff}.select-option.selected{color:#fff}.select-option.selected:before{content:"";position:absolute;left:9px;top:50%;width:5px;height:5px;border-radius:50%;background:var(--red);transform:translateY(-50%)}.source .select-menu{right:-5px;min-width:122px}.source .select-option{font-size:9px;min-width:112px}
.quality-setting{min-height:68px}.quality-controls{width:132px;display:grid;gap:7px}.quality-controls .custom-select{width:100%}.custom-select.dropup .select-menu{top:auto;bottom:calc(100% + 6px)}.bitrate-control{width:100%}.bitrate-head{display:flex;justify-content:flex-end;margin-bottom:4px}.bitrate-value{min-width:53px;padding:2px 7px;border:1px solid #2c313b;border-radius:6px;background:#171a20;color:#f3f4f6;font-size:9px;text-align:center}.bitrate-range{--fill:21%;appearance:none;-webkit-appearance:none;display:block;width:100%;height:3px;border-radius:4px;outline:0;background:linear-gradient(90deg,var(--red) 0 var(--fill),#30343d var(--fill) 100%)}.bitrate-range::-webkit-slider-thumb{appearance:none;-webkit-appearance:none;width:13px;height:13px;border:2px solid #fff;border-radius:50%;background:var(--red);box-shadow:0 2px 7px #0009;cursor:pointer}.bitrate-range:focus-visible::-webkit-slider-thumb{box-shadow:0 0 0 3px #ff3b4538}
body.recording .record .orb{animation:pulse 1.5s infinite}@keyframes pulse{50%{box-shadow:0 0 0 10px #ff3b4500,0 0 25px #ff3b4555}}
</style>
</head>
<body>
<main class="app">
<header class="header" id="dragbar"><div class="brand"><span class="mark"></span><span class="name">Fast Record</span><span class="version">v__FASTRECORD_VERSION__</span></div><div class="window-actions"><button class="icon-btn" id="pin" aria-label="Manter no topo"><svg class="icon"><use href="#i-pin"/></svg></button><button class="icon-btn" data-message="minimize" aria-label="Minimizar"><svg class="icon"><use href="#i-minus"/></svg></button><button class="icon-btn" data-message="hide" aria-label="Fechar para a bandeja"><svg class="icon"><use href="#i-close"/></svg></button></div></header>
<section class="actions">
<button class="action record" id="record"><span class="orb"><span class="record-dot"></span></span><span class="action-title">Gravar tela</span><span class="shortcut">Ctrl + Shift + R</span></button>
<button class="action" id="pause" disabled><span class="orb"><span class="pause-glyph"><i></i><i></i></span></span><span class="action-title">Pausar</span><span class="shortcut">Ctrl + P</span></button>
<button class="action" id="stop" disabled><span class="orb"><span class="stop-glyph"></span></span><span class="action-title">Parar</span><span class="shortcut">Ctrl + Shift + S</span></button>
</section>
<section class="sources">
<div class="source"><svg class="icon"><use href="#i-mic"/></svg><span class="source-title">Microfone</span><span class="source-state" id="micState">Ativado</span><button class="toggle on" id="mic" aria-label="Alternar microfone"></button></div>
<div class="source"><svg class="icon"><use href="#i-camera"/></svg><span class="source-title">Webcam</span><span class="source-state" id="camState">Desativada</span><button class="toggle" id="camera" aria-label="Alternar webcam"></button></div>
<div class="source"><svg class="icon"><use href="#i-monitor"/></svg><span class="source-title">Área da tela</span><div class="custom-select" id="areaSelect"><button class="select-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span class="select-value">Tela inteira</span><span class="chevron"></span></button><div class="select-menu" role="listbox"><button class="select-option selected" type="button" data-value="monitor">Tela inteira</button><button class="select-option" type="button" data-value="window">Janela</button><button class="select-option" type="button" data-value="region">Região</button></div></div></div>
</section>
<nav class="tabs"><button class="tab active" data-tab="files"><svg class="icon"><use href="#i-files"/></svg>Arquivos</button><button class="tab" data-tab="actions"><svg class="icon"><use href="#i-bolt"/></svg>Ações rápidas</button><button class="tab" data-tab="settings"><svg class="icon"><use href="#i-settings"/></svg>Configurações</button></nav>
<section class="content">
<div class="pane active" id="files"><div class="empty"><div class="empty-icon"><svg class="icon"><use href="#i-files"/></svg></div><strong>Nenhuma gravação ainda</strong><span>Seus vídeos aparecerão aqui depois da primeira captura.</span></div></div>
<div class="pane" id="actions"><div class="panel-list"><p class="panel-title">Atalhos</p><div class="setting"><svg class="icon"><use href="#i-folder"/></svg><div class="setting-copy"><div class="setting-name">Pasta de gravações</div><div class="setting-note">Vídeos · Fast Record</div></div><button class="secondary" data-message="open-folder">Abrir pasta</button></div><div class="setting"><svg class="icon"><use href="#i-bolt"/></svg><div class="setting-copy"><div class="setting-name">Gravação rápida</div><div class="setting-note">Funciona mesmo com a janela escondida</div></div><span class="hotkey">Ctrl Shift R</span></div></div></div>
<div class="pane" id="settings"><div class="panel-list"><p class="panel-title">Captura</p>
<div class="setting"><svg class="icon"><use href="#i-chip"/></svg><div class="setting-copy"><div class="setting-name">Encoder</div><div class="setting-note" id="capability">Detectando GPUs disponíveis…</div></div><div class="custom-select" id="engineSelect"><button class="select-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span class="select-value">Automático</span><span class="chevron"></span></button><div class="select-menu" role="listbox"><button class="select-option selected" type="button" data-value="auto">Automático</button><button class="select-option" type="button" data-value="nvenc">NVENC · NVIDIA</button><button class="select-option" type="button" data-value="amf">AMF · AMD</button><button class="select-option" type="button" data-value="software">Software · CPU</button></div></div></div>
<div class="setting quality-setting"><svg class="icon"><use href="#i-quality"/></svg><div class="setting-copy"><div class="setting-name">Qualidade do vídeo</div><div class="setting-note">Resolução e bitrate</div></div><div class="quality-controls"><div class="custom-select dropup" id="resolutionSelect"><button class="select-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span class="select-value">1080p · 1920×1080</span><span class="chevron"></span></button><div class="select-menu" role="listbox"><button class="select-option" type="button" data-value="1280x720">720p · 1280×720</button><button class="select-option selected" type="button" data-value="1920x1080">1080p · 1920×1080</button><button class="select-option" type="button" data-value="2560x1440">1440p · 2560×1440</button><button class="select-option" type="button" data-value="3840x2160">4K · 3840×2160</button></div></div><div class="bitrate-control"><div class="bitrate-head"><output class="bitrate-value" id="bitrateValue">20 Mbps</output></div><input class="bitrate-range" id="bitrate" type="range" min="4" max="80" step="1" value="20" aria-label="Bitrate do vídeo em Mbps"></div></div></div>
<div class="setting"><svg class="icon"><use href="#i-folder"/></svg><div class="setting-copy"><div class="setting-name">Destino dos vídeos</div><div class="setting-note">Pasta Vídeos do Windows</div></div><button class="secondary" data-message="open-folder">Ver</button></div></div></div>
</section>
</main>
<svg width="0" height="0" style="position:absolute"><defs>
<symbol id="i-pin" viewBox="0 0 24 24"><path d="m14 4 6 6-3 1-4 4-1 5-2-2-4 4-1-1 4-4-2-2 5-1 4-4z"/></symbol><symbol id="i-minus" viewBox="0 0 24 24"><path d="M6 12h12"/></symbol><symbol id="i-close" viewBox="0 0 24 24"><path d="m7 7 10 10M17 7 7 17"/></symbol><symbol id="i-mic" viewBox="0 0 24 24"><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"/></symbol><symbol id="i-camera" viewBox="0 0 24 24"><circle cx="12" cy="10" r="4"/><path d="M6 10a6 6 0 0 1 12 0v5H6zM4 20h16"/></symbol><symbol id="i-monitor" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="13" rx="1"/><path d="M8 21h8M12 17v4"/></symbol><symbol id="i-files" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3z"/></symbol><symbol id="i-bolt" viewBox="0 0 24 24"><path d="m13 2-8 12h7l-1 8 8-12h-7z"/></symbol><symbol id="i-settings" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></symbol><symbol id="i-folder" viewBox="0 0 24 24"><path d="M3 7h7l2 2h9v10H3z"/></symbol><symbol id="i-chip" viewBox="0 0 24 24"><rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5M15 1v5M9 18v5M15 18v5M1 9h5M1 15h5M18 9h5M18 15h5"/></symbol><symbol id="i-quality" viewBox="0 0 24 24"><path d="M4 16a8 8 0 1 1 16 0"/><path d="m12 15 4-5M6 19h12"/></symbol>
</defs></svg>
<script>
const send=m=>window.chrome?.webview?.postMessage(m);
document.querySelectorAll('[data-message]').forEach(x=>x.addEventListener('click',()=>send(x.dataset.message)));
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id===tab.dataset.tab))}));
const closeSelects=except=>document.querySelectorAll('.custom-select.open').forEach(x=>{if(x!==except){x.classList.remove('open');x.querySelector('.select-trigger').setAttribute('aria-expanded','false')}});
function customSelect(id,onChange){const root=document.getElementById(id),trigger=root.querySelector('.select-trigger'),label=root.querySelector('.select-value'),options=[...root.querySelectorAll('.select-option')];const set=value=>{const option=options.find(x=>x.dataset.value===value)||options[0];label.textContent=option.textContent;options.forEach(x=>x.classList.toggle('selected',x===option))};trigger.onclick=e=>{e.stopPropagation();const opening=!root.classList.contains('open');closeSelects(root);root.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',String(opening))};options.forEach(option=>option.onclick=e=>{e.stopPropagation();set(option.dataset.value);root.classList.remove('open');trigger.setAttribute('aria-expanded','false');onChange(option.dataset.value)});return{set}};
const areaControl=customSelect('areaSelect',value=>send('area:'+value));const engineControl=customSelect('engineSelect',value=>send('engine:'+value));const resolutionControl=customSelect('resolutionSelect',value=>send('resolution:'+value));document.addEventListener('click',()=>closeSelects());document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSelects()});
const bitrateSlider=document.getElementById('bitrate'),bitrateOutput=document.getElementById('bitrateValue');const paintBitrate=value=>{const safe=Math.max(4,Math.min(80,Number(value)||20));bitrateSlider.value=String(safe);bitrateOutput.textContent=safe+' Mbps';bitrateSlider.style.setProperty('--fill',((safe-4)/76*100)+'%')};bitrateSlider.addEventListener('input',()=>paintBitrate(bitrateSlider.value));bitrateSlider.addEventListener('change',()=>send('bitrate:'+bitrateSlider.value));paintBitrate(20);
record.onclick=()=>send('record');pause.onclick=()=>send('pause');stop.onclick=()=>send('stop');pin.onclick=()=>send('pin');mic.onclick=()=>send('toggle-mic');camera.onclick=()=>send('toggle-webcam');
dragbar.addEventListener('pointerdown',e=>{if(!e.target.closest('button'))send('drag')});
window.fastRecord={setState:s=>{document.body.classList.toggle('recording',s.recording);record.disabled=s.recording;pause.disabled=!s.recording;stop.disabled=!s.recording;pause.querySelector('.action-title').textContent=s.paused?'Continuar':'Pausar';mic.classList.toggle('on',s.microphone);camera.classList.toggle('on',s.webcam);micState.textContent=s.microphone?'Ativado':'Desativado';camState.textContent=s.webcam?'Ativada':'Desativada';pin.classList.toggle('active',s.pinned);engineControl.set(s.engine);areaControl.set(s.area);resolutionControl.set(s.resolution);paintBitrate(s.bitrate);capability.textContent=s.capability;}};
send('ready');
</script>
</body></html>
)HTML";

} // namespace fastrecord::ui
